
name: Deploy to EC2 without ecr step
on:
  push:
    branches: [ main ]
jobs:
 deploy-ec2:
    runs-on: ubuntu-latest
    env: 
      PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      HOSTNAME: ${{ secrets.EC2_HOSTNAME }}
      USER_NAME: ${{ secrets.EC2_USER_NAME }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      IMAGE_TAG: ${{ github.sha }}
      
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    steps:
      - name: Configure SSH connection
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key

      - name: Check Docker installation
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            docker --version
          '

      - name: Stop running containers
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            docker ps -aq | xargs --no-run-if-empty docker stop
          '

      - name: Remove stopped containers
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            docker ps -aq | xargs --no-run-if-empty docker rm
          '

      - name: Remove old Docker images
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} \
            'docker images | grep -i "${ECR_REPOSITORY}" | awk "{print \$3}" | xargs -r docker rmi || true'


      - name: Configure AWS credentials on EC2 and login to ECR
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
            aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
            aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
            aws configure set region ${AWS_REGION}
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
          "

      - name: Pull latest image from ECR and run container
        run: |  
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
            docker pull ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
            docker stop \$(docker ps -aq) 2>/dev/null || true
            docker rm \$(docker ps -aq) 2>/dev/null || true
            docker run -d ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}  
          "
